export const MUSCLES=["chest","back","shoulders","biceps","triceps","quads","hamstrings","glutes","calves","core","traps","forearms"];

export const EXERCISES=[
  // PULL
  {name:"Pull-ups",eq:"pull-up bar",p:[{m:"back",p:50},{m:"biceps",p:30}],s:[{m:"core",p:10},{m:"forearms",p:10}],cat:"pull",bw:true},
  {name:"Chin-ups",eq:"pull-up bar",p:[{m:"biceps",p:40},{m:"back",p:40}],s:[{m:"core",p:10},{m:"forearms",p:10}],cat:"pull",bw:true},
  {name:"Wide-grip Pull-ups",eq:"pull-up bar",p:[{m:"back",p:60},{m:"biceps",p:20}],s:[{m:"core",p:10},{m:"shoulders",p:10}],cat:"pull",bw:true},
  {name:"Commando Pull-ups",eq:"pull-up bar",p:[{m:"back",p:40},{m:"biceps",p:30}],s:[{m:"core",p:15},{m:"shoulders",p:15}],cat:"pull",bw:true},
  {name:"Barbell Rows",eq:"barbell",p:[{m:"back",p:55},{m:"biceps",p:20}],s:[{m:"shoulders",p:10},{m:"core",p:10},{m:"forearms",p:5}],cat:"pull"},
  {name:"Pendlay Rows",eq:"barbell",p:[{m:"back",p:60},{m:"biceps",p:15}],s:[{m:"core",p:10},{m:"shoulders",p:10},{m:"forearms",p:5}],cat:"pull"},
  {name:"Dumbbell Rows",eq:"dumbbells",p:[{m:"back",p:55},{m:"biceps",p:20}],s:[{m:"shoulders",p:10},{m:"core",p:10},{m:"forearms",p:5}],cat:"pull"},
  {name:"Chest-supported Incline DB Rows",eq:"dumbbells + bench",p:[{m:"back",p:60},{m:"biceps",p:20}],s:[{m:"shoulders",p:15},{m:"forearms",p:5}],cat:"pull"},
  {name:"Meadow Rows",eq:"barbell (landmine)",p:[{m:"back",p:50},{m:"biceps",p:20}],s:[{m:"shoulders",p:15},{m:"core",p:10},{m:"forearms",p:5}],cat:"pull"},
  {name:"Dumbbell Reverse Flyes",eq:"dumbbells",p:[{m:"shoulders",p:50},{m:"back",p:35}],s:[{m:"traps",p:15}],cat:"pull"},
  {name:"Incline DB Reverse Flyes",eq:"dumbbells + bench",p:[{m:"shoulders",p:50},{m:"back",p:35}],s:[{m:"traps",p:15}],cat:"pull"},
  {name:"Dumbbell Pullovers",eq:"dumbbells + bench",p:[{m:"back",p:40},{m:"chest",p:30}],s:[{m:"triceps",p:15},{m:"core",p:15}],cat:"pull"},
  {name:"EZ Bar Curls",eq:"ez curl bar",p:[{m:"biceps",p:80}],s:[{m:"forearms",p:20}],cat:"pull"},
  {name:"EZ Bar Reverse Curls",eq:"ez curl bar",p:[{m:"forearms",p:50},{m:"biceps",p:35}],s:[{m:"core",p:15}],cat:"pull"},
  {name:"Dumbbell Hammer Curls",eq:"dumbbells",p:[{m:"biceps",p:60},{m:"forearms",p:25}],s:[{m:"core",p:15}],cat:"pull"},
  {name:"Dumbbell Concentration Curls",eq:"dumbbells",p:[{m:"biceps",p:85}],s:[{m:"forearms",p:15}],cat:"pull"},
  {name:"Incline Dumbbell Curls",eq:"dumbbells + bench",p:[{m:"biceps",p:85}],s:[{m:"forearms",p:15}],cat:"pull"},
  {name:"Dumbbell Zottman Curls",eq:"dumbbells",p:[{m:"biceps",p:50},{m:"forearms",p:35}],s:[{m:"core",p:15}],cat:"pull"},
  {name:"Barbell Shrugs",eq:"barbell",p:[{m:"traps",p:80}],s:[{m:"shoulders",p:10},{m:"forearms",p:10}],cat:"pull"},
  {name:"Dumbbell Shrugs",eq:"dumbbells",p:[{m:"traps",p:80}],s:[{m:"shoulders",p:10},{m:"forearms",p:10}],cat:"pull"},
  {name:"Barbell Upright Rows",eq:"barbell",p:[{m:"shoulders",p:40},{m:"traps",p:35}],s:[{m:"biceps",p:15},{m:"forearms",p:10}],cat:"pull"},
  {name:"Dumbbell Upright Rows",eq:"dumbbells",p:[{m:"shoulders",p:40},{m:"traps",p:35}],s:[{m:"biceps",p:15},{m:"forearms",p:10}],cat:"pull"},
  {name:"Inverted Rows",eq:"barbell (low bar)",p:[{m:"back",p:50},{m:"biceps",p:25}],s:[{m:"core",p:15},{m:"shoulders",p:10}],cat:"pull",bw:true},
  {name:"Barbell Curls",eq:"barbell",p:[{m:"biceps",p:80}],s:[{m:"forearms",p:20}],cat:"pull"},
  // PUSH
  {name:"Dips",eq:"dip attachment",p:[{m:"chest",p:40},{m:"triceps",p:35}],s:[{m:"shoulders",p:25}],cat:"push",bw:true},
  {name:"Push-ups",eq:"bodyweight",p:[{m:"chest",p:45},{m:"triceps",p:30}],s:[{m:"shoulders",p:15},{m:"core",p:10}],cat:"push",bw:true},
  {name:"Diamond Push-ups",eq:"bodyweight",p:[{m:"triceps",p:50},{m:"chest",p:30}],s:[{m:"shoulders",p:10},{m:"core",p:10}],cat:"push",bw:true},
  {name:"Decline Push-ups",eq:"bodyweight + bench",p:[{m:"chest",p:40},{m:"shoulders",p:30}],s:[{m:"triceps",p:20},{m:"core",p:10}],cat:"push",bw:true},
  {name:"Pike Push-ups",eq:"bodyweight",p:[{m:"shoulders",p:60},{m:"triceps",p:25}],s:[{m:"core",p:15}],cat:"push",bw:true},
  {name:"Barbell Overhead Press",eq:"barbell",p:[{m:"shoulders",p:50},{m:"triceps",p:30}],s:[{m:"core",p:10},{m:"traps",p:10}],cat:"push"},
  {name:"Dumbbell Arnold Press",eq:"dumbbells",p:[{m:"shoulders",p:55},{m:"triceps",p:25}],s:[{m:"core",p:10},{m:"traps",p:10}],cat:"push"},
  {name:"Landmine Press",eq:"barbell (landmine)",p:[{m:"shoulders",p:40},{m:"chest",p:35}],s:[{m:"triceps",p:15},{m:"core",p:10}],cat:"push"},
  {name:"Single-arm Landmine Press",eq:"barbell (landmine)",p:[{m:"shoulders",p:40},{m:"chest",p:30}],s:[{m:"triceps",p:15},{m:"core",p:15}],cat:"push"},
  {name:"Dumbbell Bench Press",eq:"dumbbells + bench",p:[{m:"chest",p:55},{m:"triceps",p:20}],s:[{m:"shoulders",p:25}],cat:"push"},
  {name:"Incline Dumbbell Press",eq:"dumbbells + bench",p:[{m:"chest",p:40},{m:"shoulders",p:30}],s:[{m:"triceps",p:30}],cat:"push"},
  {name:"Decline Dumbbell Press",eq:"dumbbells + bench",p:[{m:"chest",p:55},{m:"triceps",p:25}],s:[{m:"shoulders",p:20}],cat:"push"},
  {name:"Dumbbell Floor Press",eq:"dumbbells",p:[{m:"chest",p:45},{m:"triceps",p:35}],s:[{m:"shoulders",p:20}],cat:"push"},
  {name:"Dumbbell Squeeze Press",eq:"dumbbells + bench",p:[{m:"chest",p:55},{m:"triceps",p:30}],s:[{m:"shoulders",p:15}],cat:"push"},
  {name:"Dumbbell Flyes",eq:"dumbbells + bench",p:[{m:"chest",p:75}],s:[{m:"shoulders",p:25}],cat:"push"},
  {name:"Incline Dumbbell Flyes",eq:"dumbbells + bench",p:[{m:"chest",p:60},{m:"shoulders",p:25}],s:[{m:"biceps",p:15}],cat:"push"},
  {name:"Close-grip Barbell Bench",eq:"barbell + bench",p:[{m:"triceps",p:50},{m:"chest",p:35}],s:[{m:"shoulders",p:15}],cat:"push"},
  {name:"EZ Bar Skull Crushers",eq:"ez curl bar + bench",p:[{m:"triceps",p:85}],s:[{m:"chest",p:10},{m:"shoulders",p:5}],cat:"push"},
  {name:"EZ Bar Overhead Extension",eq:"ez curl bar",p:[{m:"triceps",p:90}],s:[{m:"core",p:10}],cat:"push"},
  {name:"Dumbbell Lateral Raises",eq:"dumbbells",p:[{m:"shoulders",p:85}],s:[{m:"traps",p:15}],cat:"push"},
  {name:"Dumbbell Front Raises",eq:"dumbbells",p:[{m:"shoulders",p:70}],s:[{m:"chest",p:20},{m:"core",p:10}],cat:"push"},
  {name:"Dumbbell Overhead Tricep Ext",eq:"dumbbells",p:[{m:"triceps",p:90}],s:[{m:"core",p:10}],cat:"push"},
  {name:"Dumbbell Kickbacks",eq:"dumbbells",p:[{m:"triceps",p:85}],s:[{m:"shoulders",p:15}],cat:"push"},
  {name:"Plate Front Raises",eq:"bumper plate",p:[{m:"shoulders",p:70}],s:[{m:"chest",p:15},{m:"core",p:15}],cat:"push"},
  {name:"Svend Press",eq:"bumper plate",p:[{m:"chest",p:60}],s:[{m:"shoulders",p:25},{m:"triceps",p:15}],cat:"push"},
  {name:"Barbell Bench Press",eq:"barbell + bench",p:[{m:"chest",p:55},{m:"triceps",p:25}],s:[{m:"shoulders",p:20}],cat:"push"},
  {name:"Incline Barbell Bench Press",eq:"barbell + bench",p:[{m:"chest",p:45},{m:"shoulders",p:30}],s:[{m:"triceps",p:25}],cat:"push"},
  {name:"Barbell Push Press",eq:"barbell",p:[{m:"shoulders",p:45},{m:"triceps",p:25}],s:[{m:"quads",p:15},{m:"core",p:10},{m:"traps",p:5}],cat:"push"},
  // LEGS
  {name:"Belt Squat",eq:"belt + plates",p:[{m:"quads",p:55},{m:"glutes",p:30}],s:[{m:"hamstrings",p:10},{m:"calves",p:5}],cat:"legs"},
  {name:"Landmine Squat",eq:"barbell (landmine)",p:[{m:"quads",p:50},{m:"glutes",p:30}],s:[{m:"core",p:15},{m:"hamstrings",p:5}],cat:"legs"},
  {name:"Dumbbell Goblet Squat",eq:"dumbbells",p:[{m:"quads",p:50},{m:"glutes",p:30}],s:[{m:"core",p:15},{m:"hamstrings",p:5}],cat:"legs"},
  {name:"Nordic Curls",eq:"nordic curl setup",p:[{m:"hamstrings",p:85}],s:[{m:"glutes",p:10},{m:"calves",p:5}],cat:"legs",bw:true},
  {name:"Barbell Romanian Deadlifts",eq:"barbell",p:[{m:"hamstrings",p:45},{m:"glutes",p:30}],s:[{m:"back",p:15},{m:"core",p:10}],cat:"legs"},
  {name:"Dumbbell Romanian Deadlifts",eq:"dumbbells",p:[{m:"hamstrings",p:45},{m:"glutes",p:30}],s:[{m:"back",p:15},{m:"core",p:10}],cat:"legs"},
  {name:"Single-leg DB Romanian Deadlift",eq:"dumbbells",p:[{m:"hamstrings",p:40},{m:"glutes",p:35}],s:[{m:"core",p:15},{m:"back",p:10}],cat:"legs"},
  {name:"Barbell Good Mornings",eq:"barbell",p:[{m:"hamstrings",p:40},{m:"glutes",p:30},{m:"back",p:15}],s:[{m:"core",p:15}],cat:"legs"},
  {name:"Conventional Deadlift",eq:"barbell",p:[{m:"hamstrings",p:25},{m:"glutes",p:25},{m:"back",p:25}],s:[{m:"quads",p:10},{m:"core",p:10},{m:"forearms",p:5}],cat:"legs"},
  {name:"Sumo Deadlift",eq:"barbell",p:[{m:"quads",p:30},{m:"glutes",p:30},{m:"hamstrings",p:20}],s:[{m:"back",p:10},{m:"core",p:10}],cat:"legs"},
  {name:"Dumbbell Lunges",eq:"dumbbells",p:[{m:"quads",p:40},{m:"glutes",p:35}],s:[{m:"hamstrings",p:15},{m:"calves",p:10}],cat:"legs"},
  {name:"Dumbbell Reverse Lunges",eq:"dumbbells",p:[{m:"glutes",p:40},{m:"quads",p:35}],s:[{m:"hamstrings",p:15},{m:"calves",p:10}],cat:"legs"},
  {name:"Dumbbell Walking Lunges",eq:"dumbbells",p:[{m:"quads",p:40},{m:"glutes",p:30}],s:[{m:"hamstrings",p:15},{m:"calves",p:10},{m:"core",p:5}],cat:"legs"},
  {name:"Landmine Reverse Lunge",eq:"barbell (landmine)",p:[{m:"glutes",p:40},{m:"quads",p:35}],s:[{m:"core",p:15},{m:"hamstrings",p:10}],cat:"legs"},
  {name:"Dumbbell Step-ups",eq:"dumbbells + bench",p:[{m:"quads",p:45},{m:"glutes",p:35}],s:[{m:"hamstrings",p:10},{m:"calves",p:10}],cat:"legs"},
  {name:"Dumbbell Bulgarian Split Squat",eq:"dumbbells + bench",p:[{m:"quads",p:45},{m:"glutes",p:35}],s:[{m:"hamstrings",p:10},{m:"core",p:10}],cat:"legs"},
  {name:"Dumbbell Curtsy Lunge",eq:"dumbbells",p:[{m:"glutes",p:45},{m:"quads",p:30}],s:[{m:"hamstrings",p:15},{m:"core",p:10}],cat:"legs"},
  {name:"Barbell Hip Thrusts",eq:"barbell + bench",p:[{m:"glutes",p:60},{m:"hamstrings",p:25}],s:[{m:"core",p:15}],cat:"legs"},
  {name:"Single-leg Hip Thrust",eq:"bench",p:[{m:"glutes",p:65},{m:"hamstrings",p:20}],s:[{m:"core",p:15}],cat:"legs"},
  {name:"B-stance Hip Thrust",eq:"barbell + bench",p:[{m:"glutes",p:60},{m:"hamstrings",p:25}],s:[{m:"core",p:15}],cat:"legs"},
  {name:"Barbell Glute Bridge",eq:"barbell",p:[{m:"glutes",p:65},{m:"hamstrings",p:20}],s:[{m:"core",p:15}],cat:"legs"},
  {name:"Single-leg Calf Raises",eq:"bodyweight",p:[{m:"calves",p:100}],s:[],cat:"legs",bw:true},
  {name:"Barbell Calf Raises",eq:"barbell",p:[{m:"calves",p:95}],s:[{m:"core",p:5}],cat:"legs"},
  {name:"Seated Dumbbell Calf Raises",eq:"dumbbells",p:[{m:"calves",p:100}],s:[],cat:"legs"},
  {name:"Pistol Squats",eq:"bodyweight",p:[{m:"quads",p:45},{m:"glutes",p:30}],s:[{m:"core",p:15},{m:"hamstrings",p:10}],cat:"legs",bw:true},
  {name:"Sissy Squats",eq:"bodyweight",p:[{m:"quads",p:80}],s:[{m:"core",p:10},{m:"calves",p:10}],cat:"legs",bw:true},
  {name:"Wall Sit",eq:"bodyweight",p:[{m:"quads",p:70},{m:"glutes",p:20}],s:[{m:"calves",p:10}],cat:"legs",bw:true,hold:true},
  {name:"Barbell Back Squat",eq:"barbell",p:[{m:"quads",p:50},{m:"glutes",p:30}],s:[{m:"hamstrings",p:10},{m:"core",p:10}],cat:"legs"},
  {name:"Barbell Front Squat",eq:"barbell",p:[{m:"quads",p:60},{m:"glutes",p:20}],s:[{m:"core",p:15},{m:"hamstrings",p:5}],cat:"legs"},
  {name:"Barbell Lunges",eq:"barbell",p:[{m:"quads",p:40},{m:"glutes",p:35}],s:[{m:"hamstrings",p:15},{m:"calves",p:10}],cat:"legs"},
  {name:"Landmine Romanian Deadlift",eq:"barbell (landmine)",p:[{m:"hamstrings",p:45},{m:"glutes",p:30}],s:[{m:"back",p:15},{m:"core",p:10}],cat:"legs"},
  // CORE
  {name:"Hanging Leg Raises",eq:"pull-up bar",p:[{m:"core",p:85}],s:[{m:"biceps",p:10},{m:"forearms",p:5}],cat:"core",bw:true},
  {name:"Hanging Knee Raises",eq:"pull-up bar",p:[{m:"core",p:80}],s:[{m:"biceps",p:10},{m:"forearms",p:10}],cat:"core",bw:true},
  {name:"Toes to Bar",eq:"pull-up bar",p:[{m:"core",p:80}],s:[{m:"biceps",p:10},{m:"forearms",p:10}],cat:"core",bw:true},
  {name:"Windshield Wipers",eq:"pull-up bar",p:[{m:"core",p:85}],s:[{m:"shoulders",p:10},{m:"forearms",p:5}],cat:"core",bw:true},
  {name:"L-Sit Hold",eq:"dip attachment",p:[{m:"core",p:65},{m:"quads",p:15}],s:[{m:"triceps",p:10},{m:"shoulders",p:10}],cat:"core",bw:true,hold:true},
  {name:"Ab Wheel / Barbell Rollouts",eq:"barbell or wheel",p:[{m:"core",p:75}],s:[{m:"shoulders",p:15},{m:"back",p:10}],cat:"core",bw:true},
  {name:"Plank Hold",eq:"bodyweight",p:[{m:"core",p:75}],s:[{m:"shoulders",p:15},{m:"glutes",p:10}],cat:"core",bw:true,hold:true},
  {name:"Side Plank",eq:"bodyweight",p:[{m:"core",p:80}],s:[{m:"shoulders",p:10},{m:"glutes",p:10}],cat:"core",bw:true,hold:true},
  {name:"Copenhagen Plank",eq:"bench",p:[{m:"core",p:60},{m:"hamstrings",p:20}],s:[{m:"glutes",p:10},{m:"shoulders",p:10}],cat:"core"},
  {name:"Dumbbell Side Bends",eq:"dumbbells",p:[{m:"core",p:85}],s:[{m:"back",p:15}],cat:"core"},
  {name:"Farmer Carries",eq:"dumbbells",p:[{m:"core",p:30},{m:"traps",p:25},{m:"forearms",p:20}],s:[{m:"shoulders",p:15},{m:"calves",p:10}],cat:"core"},
  {name:"Suitcase Carry",eq:"dumbbell",p:[{m:"core",p:50},{m:"traps",p:20},{m:"forearms",p:15}],s:[{m:"shoulders",p:15}],cat:"core"},
  {name:"Russian Twists",eq:"dumbbell or plate",p:[{m:"core",p:85}],s:[{m:"shoulders",p:15}],cat:"core",bw:true},
  {name:"Dumbbell Woodchops",eq:"dumbbells",p:[{m:"core",p:70}],s:[{m:"shoulders",p:20},{m:"glutes",p:10}],cat:"core"},
  {name:"Landmine Rotations",eq:"barbell (landmine)",p:[{m:"core",p:70}],s:[{m:"shoulders",p:20},{m:"back",p:10}],cat:"core"},
  {name:"Dragon Flags",eq:"bench",p:[{m:"core",p:85}],s:[{m:"shoulders",p:10},{m:"back",p:5}],cat:"core"},
  {name:"Decline Sit-ups",eq:"bench",p:[{m:"core",p:80}],s:[{m:"quads",p:20}],cat:"core"},
  {name:"Dead Bugs",eq:"bodyweight",p:[{m:"core",p:80}],s:[{m:"shoulders",p:10},{m:"quads",p:10}],cat:"core",bw:true},
  {name:"Bird Dogs",eq:"bodyweight",p:[{m:"core",p:60},{m:"back",p:20}],s:[{m:"glutes",p:10},{m:"shoulders",p:10}],cat:"core",bw:true},
  {name:"Hollow Body Hold",eq:"bodyweight",p:[{m:"core",p:80}],s:[{m:"quads",p:10},{m:"shoulders",p:10}],cat:"core",bw:true,hold:true},
  {name:"Mountain Climbers",eq:"bodyweight",p:[{m:"core",p:60}],s:[{m:"shoulders",p:15},{m:"quads",p:15},{m:"calves",p:10}],cat:"core",bw:true},
];
